# Project: LinkedList
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o LinkedList.o
LINKOBJ  = main.o LinkedList.o
LIBS     = -L"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -pg
INCS     = -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Document/EMBARCODE/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = LinkedList.exe
CXXFLAGS = $(CXXINCS) -m32 -pg
CFLAGS   = $(INCS) -m32 -pg
DEL      = D:\Document\EMBARCODE\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

LinkedList.o: LinkedList.cpp
	$(CPP) -c LinkedList.cpp -o LinkedList.o $(CXXFLAGS)
